### ISSUE TITLE
Panics on reading a folder

### ISSUE THREAD

**Issue by egorsmkv** [thoas/picfit#100]
Picfit panics when it tries to serve a folder except to serve an image:

```
http: panic serving 127.0.0.1:53604: read /****************/source/content/media/market: is a directory
goroutine 43 [running]:
net/http.(*conn).serve.func1(0xc4203e4320)
	/home/yehor/Tools/Golang/1-10-2/go/src/net/http/server.go:1726 +0xd0
panic(0x1725940, 0xc42044de00)
	/home/yehor/Tools/Golang/1-10-2/go/src/runtime/panic.go:502 +0x229
github.com/thoas/picfit/errs.Handle(0x18ffc40, 0xc42044de00, 0x7f84a8caf830, 0xc4202f04d0)
	/home/yehor/Tools/Golang/1-10-2/gopath/src/github.com/thoas/picfit/errs/errs.go:21 +0xe2
github.com/thoas/picfit/server/handlers.Display(0xc4202f04d0)
	/home/yehor/Tools/Golang/1-10-2/gopath/src/github.com/thoas/picfit/server/handlers/handlers.go:39 +0x1d6
github.com/thoas/picfit/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4202f04d0)
	/home/yehor/Tools/Golang/1-10-2/gopath/src/github.com/thoas/picfit/vendor/github.com/gin-gonic/gin/context.go:107 +0x43
github.com/thoas/picfit/middleware.RestrictSizes.func2(0xc4202f04d0)
	/home/yehor/Tools/Golang/1-10-2/gopath/src/github.com/thoas/picfit/middleware/auth.go:63 +0x40
github.com/thoas/picfit/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4202f04d0)
```

**Comment by thoas** [comment]
You need to either set picfit in debug mode or setup sentry, panic will be caught by the middleware.
