### ISSUE TITLE
Panic when upscaling an animated gif

### ISSUE THREAD

**Issue by montanaflynn** [thoas/picfit#51]
Built from source and given this request:

```
http://localhost:8080/display?url=http://media2.giphy.com/media/3QJqs6pKgAfmg/giphy.gif&w=900&h=900&op=resize
```

```
PANIC: gif: image block is out of bounds
goroutine 34 [running]:
github.com/thoas/picfit/middleware.(*Recovery).ServeHTTP.func1(0x1800150, 0xc8253b08c0, 0xc82018c2a0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/middleware/middleware.go:36 +0x10a
panic(0x55d660, 0xc823034610)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/thoas/picfit/application.glob.func4(0x1800150, 0xc8253b08c0, 0xc820204240, 0xc82008c240)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/application/handlers.go:22 +0x86
github.com/thoas/picfit/application.(*Application).ServeHTTP.func1(0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/application/application.go:114 +0x2b6
net/http.HandlerFunc.ServeHTTP(0xc8200c3200, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/thoas/picfit/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000e870, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.Wrap.func1(0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba520)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x50
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc82018c4a0, 0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba520)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x44
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65cc0, 0xc82018c4a0, 0xc82018c540, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/thoas/picfit/vendor/github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc82018c3e0, 0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba4a0)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/meatballhat/negroni-logrus/middleware.go:42 +0x3ae
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65d10, 0xc82018c3e0, 0xc82018c520, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/thoas/picfit/vendor/github.com/rs/cors.(*Cors).ServeHTTP(0xc8201557a0, 0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba480)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/rs/cors/cors.go:188 +0x15a
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65ce8, 0xc8201557a0, 0xc82018c500, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/thoas/picfit/middleware.(*Logger).ServeHTTP(0xc82002e3d8, 0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba3e0)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/middleware/middleware.go:63 +0x1f4
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65c98, 0xc82002e3d8, 0xc82018c4e0, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/thoas/picfit/middleware.(*Recovery).ServeHTTP(0xc82018c2a0, 0x1800150, 0xc8253b08c0, 0xc82020c380, 0xc8253ba3c0)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/middleware/middleware.go:56 +0x83
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65c70, 0xc82018c2a0, 0xc82018c4c0, 0x1800150, 0xc8253b08c0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/thoas/picfit/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc820173740, 0x18000b8, 0xc8200640d0, 0xc82020c380)
	/Users/montanaflynn/Development/go/src/github.com/thoas/picfit/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x122
net/http.serverHandler.ServeHTTP(0xc820178d80, 0x18000b8, 0xc8200640d0, 0xc82020c380)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8201fa000)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by thoas** [comment]
We do have an issue with animated gifs, still looking for the right magic answer

**Comment by thoas** [comment]
this issue is inherent of golang itself.

Closing this as we will implement different image engine.

**Comment by montanaflynn** [comment]
Care to elaborate?
